# Generated by Django 4.2.4 on 2023-08-16 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import electrochip.services.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0003_add_default_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_description', models.TextField(max_length=200)),
                ('picture', models.URLField(blank=True, null=True)),
                ('popularity', models.PositiveIntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(default=electrochip.services.models.get_default_category, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='services', to='services.servicescategory')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
