# Generated by Django 4.2.4 on 2023-08-16 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_servicephotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicephotos',
            name='description_association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.serviceadditionaldescription'),
        ),
        migrations.AddField(
            model_name='servicephotos',
            name='service_association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.services'),
        ),
    ]
