# Generated by Django 4.2.4 on 2023-08-18 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_servicephotos_description_association_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceadditionaldescription',
            options={'verbose_name_plural': 'Services Additional Description'},
        ),
        migrations.AlterModelOptions(
            name='servicephotos',
            options={'verbose_name_plural': 'Services Photos'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='servicescategory',
            options={'verbose_name_plural': 'Services Category'},
        ),
    ]
