# Generated by Django 4.2.4 on 2023-08-16 20:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import electrochip.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0004_services'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('company_logo', models.URLField(blank=True, max_length=2083, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(4)])),
                ('address', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5)])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, validators=[electrochip.validators.validate_phone_number])),
                ('company_national_id', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(8)])),
                ('is_freelance', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_companies', to=settings.AUTH_USER_MODEL)),
                ('representatives', models.ManyToManyField(blank=True, related_name='representing_companies', to=settings.AUTH_USER_MODEL)),
                ('services', models.ManyToManyField(blank=True, to='services.services')),
            ],
        ),
    ]
