# Generated by Django 4.2.4 on 2023-08-18 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Service Provider', 'verbose_name_plural': 'Service Providers'},
        ),
        migrations.RemoveField(
            model_name='company',
            name='services',
        ),
    ]
